#ifndef ARTY_EXT_FREETYPE_GL_FREETYPE_GL_TEXT_RENDERER_HPP
#define ARTY_EXT_FREETYPE_GL_FREETYPE_GL_TEXT_RENDERER_HPP

#include <ft2build.h>
#include FT_FREETYPE_H

#endif  // ARTY_EXT_FREETYPE_GL_FREETYPE_GL_TEXT_RENDERER_HPP